# Generated by Django 6.0.6 on 2026-07-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termoassinatura',
            name='codigo_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
